---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-server

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-code-server
commonLabels:
  app: code-server

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/service-accounts.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: code-server
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
