---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-server

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-code-server
commonLabels:
  app: code-server

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/service-accounts.yaml
- resources/services.yaml

images:
  - name: code-server
    newName: ghcr.io/charlesthomas/dev-box
    newTag: v0.5.0-4.101.2

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: code-server
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: code-server
      namespace: code-server
      annotations:
        gethomepage.dev/href: https://code.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: VS Code Editor
        gethomepage.dev/group: Tools
        gethomepage.dev/icon: code-server
        gethomepage.dev/name: Code-Server
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
