---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-server
commonLabels:
  app: code-server
resources:
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- namespaces.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
