---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server
  namespace: code-server
spec:
  target:
    name: code-server
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: |-
          {{ .password }}
  data:
    - secretKey: password
      remoteRef:
        key: e86446b2-5cce-4e32-bbf6-72f0ed7bc55f
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
